### ISSUE TITLE
第一章中有关mybatis的git repo路径勘误

### ISSUE THREAD

**Issue by 380562724** [rongbo-j/mybatis-book#1]
您好，最近正在学习mybatis，购买了您的《Mybatis3源码深度解析》，目前正在学习中。第一章您有提到mybatis的三个项目：mybatis-3，spring和parent，书中写的路径两个都为parent.git（应该为一个是mybatis-3.git和一个parent.git）和一个spring.git，不知道是否是印刷的错误。

**Comment by rongbo-j** [comment]
请问具体是第几页，我查看一下

**Comment by 380562724** [comment]
第五页
![85D05D71-A83C-4A61-BC1F-777947A14FE7_1_105_c](https://user-images.githubusercontent.com/3662045/68297048-00372400-00d1-11ea-8d2d-4b3de58bd033.jpeg)

**Comment by rongbo-j** [comment]
你好 这里说的是项目名称，没有问题呢  github资源名称才是以.git结尾
