### ISSUE TITLE
SqlSession是Executor组件的外观 如何理解？

### ISSUE THREAD

**Issue by yulangde** [rongbo-j/mybatis-book#12]
在书中4.2中：
SqlSession：SqlSession是MyBatis提供的面向用户的API，表示和数据库交互时的会话对象，用于完成数据库的增删改查功能。**SqlSession是Executor组件的外观**，目的是对外提供易于理解和使用的数据库操作接口。
关于 SqlSession是Executor组件的外观 这句话如何理解？

**Comment by jiangrongbo** [comment]
Facade模式
