### ISSUE TITLE
项目maven依赖过期

### ISSUE THREAD

**Issue by yangfancoming** [rongbo-j/mybatis-book#5]
mybatis-book 项目中的pom.xml 的依赖
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.5.0-SNAPSHOT</version>
        </dependency>
依赖已经过期。 官网已经发布该版本正式版
建议将             <version>3.5.0-SNAPSHOT</version>  
改成                <version>3.5.0</version>

**Comment by rongbo-j** [comment]
把本仓库中mybatis源码作为module导入idea中，直接依赖项目源码就可以了
