### ISSUE TITLE
错别字勘误

### ISSUE THREAD

**Issue by yangfancoming** [rongbo-j/mybatis-book#6]
第3章　MyBatis常用工具类
3.2　使用ScriptRunner执行脚本  

  // 脚本文件中  SQL语句的分隔符，默认为 ;
  private String delimiter = DEFAULT_DELIMITER;
  // 是否支持SQL语句分割符，单独占一行
  private boolean fullLineDelimiter;

两行注释中 第一行使用“分隔符”  第二行使用“分割符”
有一行应该是错别字

**Comment by rongbo-j** [comment]
已修改，非常感谢🙏
